import { paymentStatusBadge } from "./labels";

type PaymentDocument = {
  orderId: string;
  provider: string;
  packageName: string;
  amount: number;
  currency: string;
  credits: number;
  status: string;
  createdAt: Date;
  paidAt: Date | null;
};

type Customer = {
  name: string;
  email: string;
};

const idr = new Intl.NumberFormat("id-ID");
const dateFmt = new Intl.DateTimeFormat("id-ID", {
  dateStyle: "medium",
  timeStyle: "short",
});

function pdfEscape(value: string) {
  return value.replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)");
}

function drawText(text: string, x: number, y: number, size = 10, font = "F1") {
  return `BT /${font} ${size} Tf ${x} ${y} Td (${pdfEscape(text)}) Tj ET\n`;
}

function drawLine(x1: number, y1: number, x2: number, y2: number) {
  return `0.85 0.89 0.94 RG ${x1} ${y1} m ${x2} ${y2} l S\n`;
}

function money(amount: number, currency: string) {
  return `${currency} ${idr.format(amount)}`;
}

function titleCase(value: string) {
  return value.slice(0, 1).toUpperCase() + value.slice(1);
}

export function paymentPdf(
  kind: "invoice" | "receipt",
  payment: PaymentDocument,
  customer: Customer,
) {
  const isReceipt = kind === "receipt";
  const isPaidInvoice = !isReceipt && payment.status === "paid";
  const status = paymentStatusBadge(payment.status).label;
  const docTitle = isReceipt ? "Receipt" : "Invoice";
  const amountLabel = isReceipt
    ? "Amount paid"
    : isPaidInvoice
      ? "Invoice total"
      : "Amount due";
  const headlineSuffix = isReceipt ? "paid" : isPaidInvoice ? "total" : "due";
  const effectiveDate = isReceipt
    ? (payment.paidAt ?? payment.createdAt)
    : payment.createdAt;
  let stream = "";
  stream += drawText(docTitle, 48, 765, 24, "F2");
  stream += drawText("Render Studio", 465, 770, 18, "F2");
  if (isReceipt) {
    stream += drawText("Status", 48, 715, 10, "F2");
    stream += drawText(status, 150, 715);
    stream += drawText("Payment date", 48, 697, 10, "F2");
    stream += drawText(dateFmt.format(effectiveDate), 150, 697);
  } else {
    stream += drawText("Invoice number", 48, 715, 10, "F2");
    stream += drawText(payment.orderId, 150, 715);
    stream += drawText("Status", 48, 697, 10, "F2");
    stream += drawText(status, 150, 697);
    stream += drawText("Issue date", 48, 679, 10, "F2");
    stream += drawText(dateFmt.format(effectiveDate), 150, 679);
  }

  stream += drawText("Billed to", 340, 715, 10, "F2");
  stream += drawText(customer.name || "Render Studio user", 340, 697);
  stream += drawText(customer.email, 340, 679);

  stream += drawLine(48, 640, 547, 640);
  stream += drawText(
    `${money(payment.amount, payment.currency)} ${headlineSuffix}`,
    48,
    604,
    20,
    "F2",
  );
  stream += drawText(amountLabel, 48, 575, 10, "F2");
  stream += drawText(money(payment.amount, payment.currency), 465, 575, 10, "F2");

  stream += drawLine(48, 535, 547, 535);
  stream += drawText("Description", 48, 510, 10, "F2");
  stream += drawText("Credits", 360, 510, 10, "F2");
  stream += drawText("Amount", 465, 510, 10, "F2");
  stream += drawLine(48, 498, 547, 498);
  stream += drawText(`${payment.packageName} credit package`, 48, 474);
  stream += drawText(`${idr.format(payment.credits)} credits`, 360, 474);
  stream += drawText(money(payment.amount, payment.currency), 465, 474);
  stream += drawLine(48, 450, 547, 450);

  stream += drawText("Subtotal", 360, 422);
  stream += drawText(money(payment.amount, payment.currency), 465, 422);
  stream += drawText("Total", 360, 400, 11, "F2");
  stream += drawText(money(payment.amount, payment.currency), 465, 400, 11, "F2");

  stream += drawText("Provider", 48, 345, 10, "F2");
  stream += drawText(titleCase(payment.provider), 150, 345);
  stream += drawText("Order ID", 48, 327, 10, "F2");
  stream += drawText(payment.orderId, 150, 327);

  stream += drawText("Generated by Render Studio", 48, 70, 9);

  return buildPdf(stream);
}

function buildPdf(stream: string) {
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    `<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}endstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((obj, index) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${index + 1} 0 obj\n${obj}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (const offset of offsets.slice(1)) {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, "utf8");
}
